In [198]:
using PyPlot
using PyCall
numpy = pyimport("numpy")
#import Pkg; Pkg.add("Numpy")

solver.quad_weightVector{Float64}
solver.rho(solver.quad_weight)Vector{Float64}


PyObject <module 'numpy' from '/Users/sakurairihito/.julia/conda/3/lib/python3.9/site-packages/numpy/__init__.py'>

In [199]:
rcParams = PyPlot.PyDict(PyPlot.matplotlib."rcParams")
rcParams["text.usetex"] = true
rcParams["font.family"] = "serif"
rcParams["font.size"] = 16
rcParams["text.latex.preamble"] = raw"\usepackage{amsmath}"

"\\usepackage{amsmath}"

In [200]:
import Pkg; Pkg.add("OMEinsum")
import Pkg; Pkg.add("SymEngine")
import SciPy
using OMEinsum, SymEngine

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`


In [178]:
import Pkg; Pkg.add("FastGaussQuadrature")
using FastGaussQuadrature

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`


In [179]:
function rho_omega(omega)
    return (1/(2*pi)) * sqrt.(4 .- omega.^2)
end
#test ok
a = [-2,2]
println(a.^2)
println(rho_omega(a))

[4, 4]
[0.0, 0.0]


In [180]:
using SparseIR
D = 2.0
temp = 0.1/D
beta = 1 / temp
wmax = 10.0 * D
lambda = beta * wmax
eps = 1e-9

wmax = lambda / beta
k = KernelFFlat(lambda)
basis = FiniteTempBasis(k, fermion, beta, eps)
L = basis.size

/Users/sakurairihito/.julia/conda/3/lib/python3.9/site-packages/sparse_ir/basis.py:208: UserWarning: 
Basis cutoff is 1e-09, which is below sqrt(eps) with
eps = 2.2e-16.  Expect singular values and basis functions
for large l to have lower precision than the cutoff.
You can install the xprec package to gain more precision.

  u, s, v = sve.compute(self.kernel, eps)


40

スパースサンプリング

In [181]:
samp_taus = TauSampling(basis)
n_taus = size(samp_taus.sampling_points) # (40,)
#println(samp_taus.sampling_points)
n_taus = n_taus[1]
#println("# of sampling points in tau=", n_taus)
#  self.cond = self.matrix.s[0] / self.matrix.s[-1]
condition_num = samp_taus.cond
#println("cond taus=", condition_num)

11.408397315310255

松原周波数でのサンプリングポインt

In [182]:
samp_matsu = MatsubaraSampling(basis)
n_matsu = size(samp_matsu.sampling_points)[1]
println(n_matsu)
#println(samp_matsu.sampling_points)
#n_matsu = n_matsu[1]
#println(n_matsu)
#println(n_matsu)
condition_matsu = samp_matsu.cond
#println("condition_matsu=" , condition_matsu)



44


17.755472693820177

In [183]:
function scale_quad(x::Vector{Float64}, w::Vector{Float64}, xmin::Float64, xmax::Float64)
    """
    Scale weights and note of quadrature to the interval [xmin, xmax]
    """
        @assert xmin < xmax
        dx = xmax - xmin
        w_ = 0.5 * dx * w
        x_ = (0.5 * dx) * (x .+ 1) .+ xmin
        return x_, w_
end

# test
x = [0.0, 1.0]
w = [0.0, 0.0]
x_min = 0.0
x_max = 1.0

res, res2 = scale_quad(x, w, x_min, x_max)
print(res)

[0.5, 1.0]

In [184]:
#Module iptsolver
struct IPTSolver
    U::Float64
    basis
    beta::Float64
    rho::Function
    quad_weight::Vector{Float64}
    quad_omega::Vector{Float64}
    samp_matsu
    samp_tau

    function IPTSolver(U::Float64, basis, rho::Function,
        omega_min::Float64, omega_max::Float64, deg_leggaus::Int64=1000)
        @assert omega_min < omega_max
        
        beta = 1 / temp
        x_, w_ = gausslegendre(deg_leggaus)
        quad_omega, quad_weight = scale_quad(x_, w_, omega_min, omega_max)
        samp_matsu = MatsubaraSampling(basis)
        samp_tau = TauSampling(basis)
        new(
            U,
            basis,
            beta,
            rho,
            quad_weight,
            quad_omega,
            samp_matsu,
            samp_tau
        )
    end
end

#end

U = 2.0
typeof(rho_omega)
solver = IPTSolver(U, basis, rho_omega, -2.0, 2.0)

IPTSolver(2.0, FiniteTempBasis(PyObject <sparse_ir.basis.FiniteTempBasis object at 0x16aa54e80>, SparseIR.PiecewiseLegendrePoly(PyObject <sparse_ir.poly.PiecewiseLegendrePoly object at 0x2b21f3d90>), SparseIR.PiecewiseLegendreFT(PyObject <sparse_ir.poly.PiecewiseLegendreFT object at 0x2b21f3e80>), SparseIR.PiecewiseLegendrePoly(PyObject <sparse_ir.poly.PiecewiseLegendrePoly object at 0x2b21f3f10>), [1.5188172858544782, 1.3683764503479776, 0.9700979242501672, 0.7360423263399413, 0.4981868574009639, 0.3429903559295014, 0.22679199175643916, 0.1490964516649698, 0.09624381680055877, 0.06148251008737195  …  6.525699976379233e-7, 3.4949923094095277e-7, 1.8599868547215032e-7, 9.836616393910872e-8, 5.1698714251134476e-8, 2.7004505931740732e-8, 1.4019679619414097e-8, 7.2344717495791176e-9, 3.710758760920353e-9, 1.8920164394565375e-9], fermion, 40), 20.0, rho_omega, [1.482667683286414e-5, 3.451353954747845e-5, 5.422921313041171e-5, 7.394688401287099e-5, 9.36643341394255e-5, 0.00011338101302303457

In [185]:
function make_gloc_iv(solver::IPTSolver, sigma_iv::Vector{Complex{Float64}})

    """
    Compute G_loc(iv) from Sigma_iv
    G_loc(iv) \\simeq \\sum_q w_q rho(x_q)/(iv - w_q - \\Sigma(iv))
    """

    iv = 1im * solver.samp_matsu.sampling_points * π/solver.beta 
    #gloc_iv = Vector{Complex{64}}(undef, length(iv)) #undefは空っぽの配列（型は指定しない）
    #for iq in 1:length(solver.quad_weight)
    #end
    println("solver.quad_weight", typeof(solver.quad_weight))
    println("solver.rho(solver.quad_weight)", typeof(solver.rho(solver.quad_weight))) 
    r = numpy.einsum("q,q,wq->w",
            solver.quad_weight,
            solver.rho(solver.quad_omega),
            1/((iv .- sigma_iv)[:,:] .- solver.quad_omega[:,:]),
            optimize = True
        )
    return r
end

make_gloc_iv (generic function with 1 method)

r = ein"q,q,wq->w"(
            solver.quad_weight,
            solver.rho(solver.quad_weight),
            1/((iv-sigma_iv)[:,:] .- solver.quad_omega[:,:])
        )
    return r

In [186]:
U = 2.0
#typeof(rho_omega)
solver = IPTSolver(U, basis, rho_omega, -2.0, 2.0)
#println("solver.quad_weight",solver.quad_weight)
println("rho(solver.quad_weight)", size(rho_omega(solver.quad_weight)))
println("solver.quad_omega=", typeof(solver.quad_omega))
println("solver.quad_omega=", typeof(solver.quad_omega[:,:]))
println("solver.quad_omega=", size(solver.quad_omega[:,:]))
#sigma_iv_ = make_sigma_ini(solver)
#new_sigma_iv = new_sigma_iv(solver, sigma_iv_)

v = 1im * solver.samp_matsu.sampling_points * π/solver.beta 
println("v", size(v[:,:]))

rho(solver.quad_weight)(1000,)
solver.quad_omega=Vector{Float64}
solver.quad_omega=Matrix{Float64}
solver.quad_omega=(1000, 1)
v(44, 1)


In [187]:
function g0_iv(solver::IPTSolver, sigma_iv::Vector{Complex{Float64}}) # sigma_ivは適当な初期値が入る（）
    return 1/(1/make_gloc_iv(solver) .+ sigma_iv)
end

g0_iv (generic function with 2 methods)

In [191]:
function sigma_iv(solver::IPTSolver, g0_iv) #g0_ivは上で定義した関数の値が入る
    """
    Compute Sigma(tau) from \\mathcal{G}(iv)
    """
    g0_IR = solver.samp_matsu.fit(g0_iv, axis=1)
    g0_tau = solver.samp_tau.evaluate(g0_IR)
    sigma_tau = (solver.U)^2 .* (g0_tau).^2 .* g0_tau[end:-1:1]
    sigma_IR = solver.samp_tau.fit(sigma_tau)
    return solver.samp_matsu.evaluate(sigma_IR, axis=1)
end

sigma_iv (generic function with 1 method)

In [193]:
function new_sigma_iv(solver::IPTSolver, sigma_iv)
    gloc_iv = make_gloc_iv(solver, sigma_iv)
    g0_iv = g0_iv(gloc_iv, sigma_iv)
    r = sigma_iv(solver, g0_iv)
    return r
end


new_sigma_iv (generic function with 1 method)

In [194]:
sigma_ini = Vector{Complex{Float64}}
sigma_ini = zeros(ComplexF64, )
#n_matsu = size(samp_matsu.sampling_points)[1]

function make_sigma_ini(solver::IPTSolver)
    samp_matsu = solver.samp_matsu
    n_matsu = size(samp_matsu.sampling_points)[1]
    return zeros(ComplexF64, n_matsu)
end

make_sigma_ini (generic function with 1 method)

In [195]:
#sigma_ini = make_sigma_ini(solver);


In [196]:
niter = 10000
mixing = 0.1

U = 2.0 .* [range(0.001/D, 6.5/D , length=8);] 

#solver = IPTSolver(u, basis, rho_omega, omega_min, omega_max)


function normalize_factor(u, basis, rho_omega, omega_min::Float64, omega_max::Float64, sigma_iv::Vector{Complex{Float64}})
    solver = IPTSolver(u, basis, rho_omega, omega_min, omega_max)

    #if sigma_ini == "None"
    #   sigma_ini = [0] #sigma_iv::Vector{Complex{Float64}})
    #end
    #sigma_ini = Vector
    #sigma_iv = copy(sigma_iv)

    new_sigma_iv = make_sigma_ini(solver)

    for iter in range(1,10)
        new_sigma_iv[1] = new_sigma_iv(solver, sigma_iv)[1]
        rerr = findmax(abs.(new_sigma_iv - sigma_iv))[1]/findmax(abs.(sigma_iv))[1]
        if rerr < 1e-5
            break
        end
        sigma_iv = mixing * new_sigma_iv .+ (1 - mixing) * sigma_iv
    end

    center = length(sigma_iv)÷2 
    z = 1/(1-(imag.(sigma_iv)[center]-imag(sigma_iv)[center-1])/(solver.samp_matsu.sampling_points[center]-solver.samp_matsu.sampling_points[center-1]))

    return z, sigma_iv
end

normalize_factor (generic function with 1 method)

In [197]:
u = 1.0
omega_min = -2.0
omega_max = 2.0
sigma_iv_ = make_sigma_ini(solver)
new_sigma_iv = new_sigma_iv(solver, sigma_iv_)
#normalize_factor(u, basis, rho_omega, omega_min, omega_max,sigma_iv_)

DimensionMismatch: DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 44 and 1000")

In [94]:
Z = []
Simga_U = []
for u in U:
    zz, s_u = normalize_factor(u, basis, rho_omega, omega_min, omega_max,sigma_iv)

ErrorException: syntax: line break in ":" expression

In [95]:
length(sigma_ini)
length(sigma_ini)÷2

solver.quad_weightVector{Float64}
solver.rho(solver.quad_weight)Vector{Float64}


0

プレイグランド

In [102]:
x_, w_ = gausslegendre(deg_leggaus=1000)
quad_omega, quad_weight = scale_quad(x_, w_, omega_min, omega_max)

MethodError: MethodError: no method matching gausslegendre(; deg_leggaus=1000)
Closest candidates are:
  gausslegendre(!Matched::Integer) at ~/.julia/packages/FastGaussQuadrature/BRLTf/src/gausslegendre.jl:22 got unsupported keyword argument "deg_leggaus"

using FastGaussQuadrature,SpecialPolynomials

In [103]:
Pkg.add("SpecialPolynomials")
using FastGaussQuadrature,SpecialPolynomials

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`


In [104]:
# ガウスの積分公式を使っている。不定積分を解析的に求めるのではなく、有限な数のサンプル点における値を利用する。
# http://nkl.cc.u-tokyo.ac.jp/12e/02-FEM/GaussLegendre.pdf
x, w = gausslegendre(3)

([-0.7745966692414834, 0.0, 0.7745966692414834], [0.5555555555555556, 0.8888888888888888, 0.5555555555555556])

In [105]:
using LinearAlgebra
myfunc(x) = x^4
I = dot(w,myfunc.(x))
print("x",x)
print
println(I)
@assert I ≈ 2/5


0.4000000000000001


In [106]:
p3 = SpecialPolynomials.basis(Legendre, 3)
x2 = collect(range(-1,1,length=1000))

plt.figure()
plt.plot(x2,p3.(x2),label="P_3")
plt.plot(x,[0,0,0],marker="o")
plt.xlabel("x")
plt.ylabel("3rd basis of Legendre polynomials")
plt.savefig("check_gaussquad.pdf")

In [107]:
x2 = collect(range(-1,1,length=1000))

1000-element Vector{Float64}:
 -1.0
 -0.997997997997998
 -0.995995995995996
 -0.993993993993994
 -0.991991991991992
 -0.98998998998999
 -0.987987987987988
 -0.985985985985986
 -0.983983983983984
 -0.9819819819819819
  ⋮
  0.983983983983984
  0.985985985985986
  0.987987987987988
  0.98998998998999
  0.991991991991992
  0.993993993993994
  0.995995995995996
  0.997997997997998
  1.0

In [108]:
range(-1,1,length=1000)

-1.0:0.002002002002002002:1.0

In [109]:
A = rand(Float64, 2, 2)

2×2 Matrix{Float64}:
 0.284444  0.389023
 0.381043  0.223978

In [111]:
A[end:-1:1, :]

2×2 Matrix{Float64}:
 0.381043  0.223978
 0.284444  0.389023

In [112]:
A[1:2, :]

2×2 Matrix{Float64}:
 0.284444  0.389023
 0.381043  0.223978

In [113]:
A[end:-1:1, :, :]

2×2×1 Array{Float64, 3}:
[:, :, 1] =
 0.381043  0.223978
 0.284444  0.389023

In [114]:
B = rand(Float64, 3, 3)
#println(B)

3×3 Matrix{Float64}:
 0.838049  0.249068  0.970057
 0.637646  0.366873  0.908885
 0.798598  0.96509   0.843229

In [115]:
# 列を交換した。全ての列に関して逆順にした。
B[:, end:-1:1]

3×3 Matrix{Float64}:
 0.970057  0.249068  0.838049
 0.908885  0.366873  0.637646
 0.843229  0.96509   0.798598

In [116]:
B[end:-1:1, :]

3×3 Matrix{Float64}:
 0.798598  0.96509   0.843229
 0.637646  0.366873  0.908885
 0.838049  0.249068  0.970057

In [117]:
C = rand(Float64, 4, 4)

4×4 Matrix{Float64}:
 0.288775  0.193691  0.482939  0.0434422
 0.676368  0.530307  0.383387  0.611905
 0.688957  0.230515  0.680132  0.309188
 0.385985  0.747789  0.631511  0.44173

In [118]:
C[end:-1:1, :]

4×4 Matrix{Float64}:
 0.385985  0.747789  0.631511  0.44173
 0.688957  0.230515  0.680132  0.309188
 0.676368  0.530307  0.383387  0.611905
 0.288775  0.193691  0.482939  0.0434422

In [119]:
C[:,None]

UndefVarError: UndefVarError: None not defined

In [120]:
A = Array{Int}(undef,2,4,2)

2×4×2 Array{Int64, 3}:
[:, :, 1] =
 3417225421390113141  0  0  0
        293168366641  0  0  0

[:, :, 2] =
 0  0  0  0
 0  0  0  0

In [121]:
A[..,1] 

UndefVarError: UndefVarError: .. not defined

In [122]:
A = Array{Int}(undef,3,3)

3×3 Matrix{Int64}:
 7598251388580490081  7022329182242039649  7593476290060186227
 8460625631237138792  8746397786379086196  3345612038820754292
 7738135719211788652  3407352825314488179           4294995827

In [123]:
A[..,1]

UndefVarError: UndefVarError: .. not defined

In [124]:
A = rand(3)

3-element Vector{Float64}:
 0.2633701009362738
 0.35134549825135764
 0.9286167114491054

In [125]:
A[:,:] #:で範囲外の次元を増やしてくれる。あるいは、ある次元に沿った要素を全て指定してくれる、

3×1 Matrix{Float64}:
 0.2633701009362738
 0.35134549825135764
 0.9286167114491054

In [126]:
#juliaで，aからbまで等間隔にp個区切りたかったら，
a = 1
b = 2
p = 10
c = [ range(a,b,length=p); ]
println(c)
d = collect(range(a, b, length=p))
println(d)
length(d)


[1.0, 1.1111111111111112, 1.2222222222222223, 1.3333333333333333, 1.4444444444444444, 1.5555555555555556, 1.6666666666666667, 1.7777777777777777, 1.8888888888888888, 2.0]
[1.0, 1.1111111111111112, 1.2222222222222223, 1.3333333333333333, 1.4444444444444444, 1.5555555555555556, 1.6666666666666667, 1.7777777777777777, 1.8888888888888888, 2.0]


10

In [127]:
e = collect(1.0:1.0:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [128]:
function f(a, s="None")
    if s == "None"
        println(a)
    end
end

f(1)


1


In [129]:
using OMEinsum
catty = fill(Basic(:🐱), 2, 2)
fish = fill(Basic(:🐟), 2, 3, 2)
snake = fill(Basic(:🐍), 3, 3)
medicine = ein"ij,jki,kk->k"(catty, fish, snake)


3-element Vector{Basic}:
 4*🐱*🐍*🐟
 4*🐱*🐍*🐟
 4*🐱*🐍*🐟

In [130]:
complex(0)

0 + 0im

In [131]:
for iter in range(1,10)
    println(iter)
end


1
2
3
4
5
6
7
8
9
10


In [132]:
ComplexF64()

MethodError: MethodError: no method matching ComplexF64()
Closest candidates are:
  (::Type{T})(!Matched::AbstractChar) where T<:Union{AbstractChar, Number} at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/char.jl:50
  (::Type{T})(!Matched::Base.TwicePrecision) where T<:Number at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/twiceprecision.jl:255
  Complex{T}(!Matched::Complex) where T<:Real at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/complex.jl:43
  ...

In [133]:
Array{ComplexF64}(42)

MethodError: MethodError: no method matching (Array{ComplexF64})(::Int64)
Closest candidates are:
  (Array{T})(!Matched::LinearAlgebra.LQPackedQ{T, S} where S<:AbstractMatrix{T}) where T at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/lq.jl:168
  (Array{T})(!Matched::UniformScaling, !Matched::Tuple{Int64, Int64}) where T at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/uniformscaling.jl:494
  (Array{T})(!Matched::UniformScaling, !Matched::Integer, !Matched::Integer) where T at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/uniformscaling.jl:495
  ...

[0.5, 1.0]